[package]
name = "rocksdb-waltest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.rocksdb]
version = "0.21"
default-features = false
features = [ "lz4" ]